on:
  pull_request:
  push:
    branches:
      - main

name: continuous-integration

jobs:
  test:
    runs-on: ubuntu-latest
    name: Nushell formatter test
    steps:
      - uses: actions/checkout@v4
      - uses: hustcer/setup-nu@main
        with:
          version: "*"
      - run: nu --version
      - run: nu run_test.nu
